// prisma/seed.ts

import { Prisma, PrismaClient } from '@prisma/client';
export const A319_DATA = [
  {
    registration: 'PT-TMT',
    type: '319-132',
    engine: '',
    active: true,
    aircraftModelCode: 'A319',
  },
  {
    registration: 'PT-TML',
    type: '319-132',
    engine: '',
    active: true,
    aircraftModelCode: 'A319',
  },
  {
    registration: 'PR-MBN',
    type: '319-132',
    engine: '',
    active: true,
    aircraftModelCode: 'A319',
  },
  {
    registration: 'PR-MBU',
    type: '319-132',
    engine: '',
    active: true,
    aircraftModelCode: 'A319',
  },
  {
    registration: 'PR-MBV',
    type: '319-132',
    engine: '',
    active: true,
    aircraftModelCode: 'A319',
  },
  {
    registration: 'PR-MBW',
    type: '319-132',
    engine: '',
    active: true,
    aircraftModelCode: 'A319',
  },
  {
    registration: 'PR-MYC',
    type: '319-112',
    engine: '',
    active: true,
    aircraftModelCode: 'A319',
  },
  {
    registration: 'PT-TMA',
    type: '319-132',
    engine: '',
    active: true,
    aircraftModelCode: 'A319',
  },
  {
    registration: 'PT-TMB',
    type: '319-132',
    engine: '',
    active: true,
    aircraftModelCode: 'A319',
  },
  {
    registration: 'PT-TMC',
    type: '319-132',
    engine: '',
    active: true,
    aircraftModelCode: 'A319',
  },
  {
    registration: 'PT-TMD',
    type: '319-132',
    engine: '',
    active: true,
    aircraftModelCode: 'A319',
  },
  {
    registration: 'PT-TME',
    type: '319-132',
    engine: '',
    active: true,
    aircraftModelCode: 'A319',
  },
  {
    registration: 'PT-TMO',
    type: '319-132',
    engine: '',
    active: true,
    aircraftModelCode: 'A319',
  },
  {
    registration: 'PR-MYL',
    type: '319-112',
    engine: '',
    active: true,
    aircraftModelCode: 'A319',
  },
  {
    registration: 'PR-MYM',
    type: '319-112',
    engine: '',
    active: true,
    aircraftModelCode: 'A319',
  },
  {
    registration: 'PT-TMG',
    type: '319-132',
    engine: '',
    active: true,
    aircraftModelCode: 'A319',
  },
  {
    registration: 'PT-TPA',
    type: '319-112',
    engine: '',
    active: true,
    aircraftModelCode: 'A319',
  },
  {
    registration: 'PT-TPB',
    type: '319-112',
    engine: '',
    active: true,
    aircraftModelCode: 'A319',
  },
  {
    registration: 'PT-TMI',
    type: '319-132',
    engine: '',
    active: true,
    aircraftModelCode: 'A319',
  },
];

export const A320_DATA = [
  {
    registration: 'PR-MBG',
    type: '320-232',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MAK',
    type: '320-232',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MAG',
    type: '320-232',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MBA',
    type: '320-232',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MBF',
    type: '320-232',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MBH',
    type: '320-232',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MHA',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MHG',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MHI',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MHJ',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MHK',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MHE',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MHF',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MHM',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MHP',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MHQ',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MHR',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MHU',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MHX',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MHW',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MHZ',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MYA',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MYH',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MYI',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MYJ',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MYK',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-TQB',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-TQC',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MYN',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MYO',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MYP',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MYQ',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MYR',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MYT',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MYV',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MYW',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MYX',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MYY',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-MYZ',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-TYA',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-TYD',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-TYF',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-TYH',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-TYI',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-TYJ',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-TYK',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-TYL',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-TYM',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-TYN',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-TYO',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-TYS',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-TYT',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-TYP',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-TYQ',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-TYR',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-TYU',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-TYV',
    type: '320-214',
    engine: '',
    active: true,
    aircraftModelCode: 'A320',
  },
  {
    registration: 'PR-XBB',
    type: '320-273N',
    engine: '',
    active: true,
    aircraftModelCode: 'A20N',
  },
  {
    registration: 'PR-XBA',
    type: '320-273N',
    engine: '',
    active: true,
    aircraftModelCode: 'A20N',
  },
  {
    registration: 'PR-XBD',
    type: '320-273N',
    engine: '',
    active: true,
    aircraftModelCode: 'A20N',
  },
  {
    registration: 'PR-XBE',
    type: '320-273N',
    engine: '',
    active: true,
    aircraftModelCode: 'A20N',
  },
  {
    registration: 'PR-XBF',
    type: '320-273N',
    engine: '',
    active: true,
    aircraftModelCode: 'A20N',
  },
  {
    registration: 'PR-XBI',
    type: '320-271N',
    engine: '',
    active: true,
    aircraftModelCode: 'A20N',
  },
  {
    registration: 'PR-XBJ',
    type: '320-271N',
    engine: '',
    active: true,
    aircraftModelCode: 'A20N',
  },
  {
    registration: 'PR-XBK',
    type: '320-271N',
    engine: '',
    active: true,
    aircraftModelCode: 'A20N',
  },
  {
    registration: 'PR-XBL',
    type: '320-271N',
    engine: '',
    active: true,
    aircraftModelCode: 'A20N',
  },
  {
    registration: 'PR-XBM',
    type: '320-271N',
    engine: '',
    active: true,
    aircraftModelCode: 'A20N',
  },
  {
    registration: 'PR-XBN',
    type: '320-271N',
    engine: '',
    active: true,
    aircraftModelCode: 'A20N',
  },
  {
    registration: 'PR-XBO',
    type: '320-271N',
    engine: '',
    active: true,
    aircraftModelCode: 'A20N',
  },
  {
    registration: 'PR-XBH',
    type: '320-271N',
    engine: '',
    active: true,
    aircraftModelCode: 'A20N',
  },
  {
    registration: 'PR-XBP',
    type: '320-271N',
    engine: '',
    active: true,
    aircraftModelCode: 'A20N',
  },
  {
    registration: 'PR-XBG',
    type: '320-271N',
    engine: '',
    active: true,
    aircraftModelCode: 'A20N',
  },
  {
    registration: 'PR-XBQ',
    type: '320-271N',
    engine: '',
    active: true,
    aircraftModelCode: 'A20N',
  },
  {
    registration: 'PR-XBR',
    type: '320-271N',
    engine: '',
    active: true,
    aircraftModelCode: 'A20N',
  },
];

export const A321_DATA = [
  {
    registration: 'PT-MXA',
    type: '321-231',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-MXB',
    type: '321-231',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-MXC',
    type: '321-231',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-MXD',
    type: '321-231',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-MXE',
    type: '321-231',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-MXF',
    type: '321-231',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-MXG',
    type: '321-231',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-MXH',
    type: '321-231',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-MXI',
    type: '321-231',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-MXJ',
    type: '321-231',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-MXL',
    type: '321-231',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-MXM',
    type: '321-231',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-MXN',
    type: '321-231',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-MXO',
    type: '321-231',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-MXP',
    type: '321-231',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-MXQ',
    type: '321-231',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-XPA',
    type: '321-211',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-XPB',
    type: '321-211',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-XPC',
    type: '321-211',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-XPD',
    type: '321-211',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-XPE',
    type: '321-211',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-XPF',
    type: '321-211',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-XPG',
    type: '321-211',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-XPH',
    type: '321-211',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-XPI',
    type: '321-211',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-XPJ',
    type: '321-211',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-XPL',
    type: '321-211',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-XPM',
    type: '321-211',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-XPN',
    type: '321-211',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-XPQ',
    type: '321-211',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PT-XPO',
    type: '321-211',
    engine: '',
    active: true,
    aircraftModelCode: 'A321',
  },
  {
    registration: 'PS-LBA',
    type: '321-271NX',
    engine: '',
    active: true,
    aircraftModelCode: 'A21N',
  },
  {
    registration: 'PS-LBB',
    type: '321-271NX',
    engine: '',
    active: true,
    aircraftModelCode: 'A21N',
  },
  {
    registration: 'PS-LBC',
    type: '321-271NX',
    engine: '',
    active: true,
    aircraftModelCode: 'A21N',
  },
  {
    registration: 'PS-LBE',
    type: '321-271NX',
    engine: '',
    active: true,
    aircraftModelCode: 'A21N',
  },
  {
    registration: 'PS-LBF',
    type: '321-271NX',
    engine: '',
    active: true,
    aircraftModelCode: 'A21N',
  },
  {
    registration: 'PS-LBG',
    type: '321-271NX',
    engine: '',
    active: true,
    aircraftModelCode: 'A21N',
  },
  {
    registration: 'PS-LBJ',
    type: '321-271NX',
    engine: '',
    active: true,
    aircraftModelCode: 'A21N',
  },
  {
    registration: 'PS-LBH',
    type: '321-271NX',
    engine: '',
    active: true,
    aircraftModelCode: 'A21N',
  },
  {
    registration: 'PS-LBI',
    type: '321-271NX',
    engine: '',
    active: true,
    aircraftModelCode: 'A21N',
  },
];

const aircraftModelData: Prisma.AircraftModelCreateInput[] = [
  { code: 'A319', manufacturer: 'Airbus', model: 'A319' },
  { code: 'A320', manufacturer: 'Airbus', model: 'A320' },
  { code: 'A321', manufacturer: 'Airbus', model: 'A321' },
  { code: 'A20N', manufacturer: 'Airbus', model: 'A320neo' },
  { code: 'A21N', manufacturer: 'Airbus', model: 'A321neo' },
];

// initialize Prisma Client
const prisma = new PrismaClient();

async function main() {
  const roles: Prisma.RoleCreateInput[] = [
    {
      name: 'Crew',
    },
  ];

  await prisma.$transaction([
    ...aircraftModelData.map((cur) => {
      return prisma.aircraftModel.upsert({
        where: { code: cur.code },
        update: {},
        create: cur,
      });
    }),
    ...roles.map((role) =>
      prisma.role.upsert({
        where: { name: role.name },
        update: {},
        create: role,
      }),
    ),

    ...[...A320_DATA, ...A319_DATA, ...A321_DATA].map((aircraft) =>
      prisma.aircraft.upsert({
        where: {
          registration: aircraft.registration,
        },
        update: { ...aircraft },
        create: {
          ...aircraft,
        },
      }),
    ),
  ]);
}

// execute the main function
main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    // close Prisma Client at the end
    await prisma.$disconnect();
  });
