-- AlterTable
ALTER TABLE "Route" ALTER COLUMN "eobt" SET DATA TYPE TEXT,
ALTER COLUMN "speed" SET DATA TYPE TEXT,
ALTER COLUMN "flight_level" SET DATA TYPE TEXT,
ALTER COLUMN "eet" SET DATA TYPE TEXT,
ALTER COLUMN "route_status_id" SET DATA TYPE TEXT;
