
// This file is automatically generated by a script. DO NOT EDIT DIRECTLY.

import { Event } from '@prisma/client';
import { SeverityId } from './severity';



export interface GeneratedEvent extends Event {
  logicalId: string;
  name: string;
  reference: string;
  description: string;
  severityId: SeverityId;
}

type SequentialIdMap = {
  [key: string]: GeneratedEvent;
};

// =========================================================
// DYNAMICALLY GENERATED INTERFACES FOR LITERAL KEYS
// =========================================================

// Maps SeverityId names (e.g., "STANDARD_COMPLIANCE") to SequentialIdMap
export type SeverityMap = {
  'STANDARD_COMPLIANCE'?: SequentialIdMap;
  'PROACTIVE_EXCELLENCE'?: SequentialIdMap;
  'PROCEDURAL_DEVIATION'?: SequentialIdMap;
  'SAFETY_COMPROMISE'?: SequentialIdMap;
};

export type ItemMapFor_AT_START_CLEARANCE = {
    'PUSHBACKSTART_UP_CLEARANCE'?: SeverityMap;
    'WINDOWS_AND_DOORS'?: SeverityMap;
    'EXTERIOR_LIGHTS'?: SeverityMap;
    'THRUST_LEVERS'?: SeverityMap;
    'ACCU_PRESSURE'?: SeverityMap;
    'PARKING_BRAKE_AND_NOSEWHEEL_STEERING'?: SeverityMap;
};

export type SubPhaseMapFor_BEFORE_PUSHBACK_OR_START = {
    'AT_START_CLEARANCE'?: ItemMapFor_AT_START_CLEARANCE;
};

// Main CheckListOutput type with literal phase keys
export type CheckListOutput = {
  'BEFORE_PUSHBACK_OR_START'?: SubPhaseMapFor_BEFORE_PUSHBACK_OR_START;
};


export const eventList: CheckListOutput = {
  "BEFORE_PUSHBACK_OR_START": {
    "AT_START_CLEARANCE": {
      "ACCU_PRESSURE": {
        "STANDARD_COMPLIANCE": {
          "01": {
            "id": "placeholder-prisma-id",
            "logicalId": "[BEFORE_PUSHBACK_OR_START][AT_START_CLEARANCE][ACCU_PRESSURE][STANDARD_COMPLIANCE][01]",
            "name": "ACCU PRESS indicator",
            "reference": "",
            "description": "green band",
            "severityId": 1
          }
        },
        "SAFETY_COMPROMISE": {
          "01": {
            "id": "placeholder-prisma-id",
            "logicalId": "[BEFORE_PUSHBACK_OR_START][AT_START_CLEARANCE][ACCU_PRESSURE][SAFETY_COMPROMISE][01]",
            "name": "ACCU PRESS indicator",
            "reference": "",
            "description": "\n<p>When the ACCU (Accumulator) pressure indication is outside the green band, it means that the hydraulic pressure stored in the brake accumulators is insufficient. This has direct and critical implications for operational safety:</p>\n\n<ul>\n    <li><strong>Risk of uncontrolled aircraft movement:</strong> Low accumulator pressure limits the friction force applied to the brake discs, which can lead to unwanted aircraft movement, especially during pushback, when the engines are not yet providing full hydraulic pressure.</li>\n    <li><strong>Ineffectiveness of the parking brake:</strong> The parking brake directly depends on the hydraulic pressure supplied by the accumulators when the engines are not running. If the ACCU pressure is low, the parking brake will not be able to safely hold the aircraft, allowing it to roll freely.</li>\n    <li><strong>Compromised emergency braking applications:</strong> The accumulators provide a critical energy reserve for a limited number of braking applications, especially in scenarios where primary hydraulic power sources are not operational. If the ACCU pressure is already low before pushback, this safety margin is severely reduced, limiting the number of brake applications available in an emergency, such as an aborted pushback or a subsequent hydraulic failure.</li>\n</ul>\n\n<p>In summary, an indication outside the green band is not just a technical deviation, but a direct warning of compromised braking capability, which increases the risk of ground incidents and compromises overall operational safety.</p>",
            "severityId": 4
          }
        }
      }
    }
  }
};
