import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding exam system...');

  // Create question tags using upsert
  const tags = await Promise.all([
    prisma.questionTag.upsert({
      where: { name: 'Aerodynamics' },
      update: {},
      create: {
        name: 'Aerodynamics',
        description: 'Questions about aircraft aerodynamics and flight principles',
        color: '#3B82F6',
      },
    }),
    prisma.questionTag.upsert({
      where: { name: 'Navigation' },
      update: {},
      create: {
        name: 'Navigation',
        description: 'Questions about navigation systems and procedures',
        color: '#10B981',
      },
    }),
    prisma.questionTag.upsert({
      where: { name: 'Meteorology' },
      update: {},
      create: {
        name: 'Meteorology',
        description: 'Questions about weather and meteorological conditions',
        color: '#F59E0B',
      },
    }),
    prisma.questionTag.upsert({
      where: { name: 'Regulations' },
      update: {},
      create: {
        name: 'Regulations',
        description: 'Questions about aviation regulations and procedures',
        color: '#EF4444',
      },
    }),
  ]);

  console.log(`✅ Created/Updated ${tags.length} question tags`);

  // Create sample questions using upsert
  const questions = [
    {
      uniqueKey: 'aerodynamics-lift-primary-force',
      tagId: tags[0].id, // Aerodynamics
      statement: 'What is the primary force that keeps an aircraft in flight?',
      explanation: 'Lift is the primary force that keeps an aircraft in flight, generated by the wings as air flows over them.',
      difficulty: 2,
      alternatives: [
        { text: 'Thrust', isCorrect: false },
        { text: 'Lift', isCorrect: true },
        { text: 'Weight', isCorrect: false },
        { text: 'Drag', isCorrect: false },
      ],
    },
    {
      uniqueKey: 'aerodynamics-lift-airspeed',
      tagId: tags[0].id, // Aerodynamics
      statement: 'What happens to lift when airspeed increases?',
      explanation: 'Lift increases with the square of airspeed, so doubling airspeed quadruples lift.',
      difficulty: 3,
      alternatives: [
        { text: 'Lift decreases', isCorrect: false },
        { text: 'Lift increases', isCorrect: true },
        { text: 'Lift remains constant', isCorrect: false },
        { text: 'Lift becomes negative', isCorrect: false },
      ],
    },
    {
      uniqueKey: 'navigation-vor-meaning',
      tagId: tags[1].id, // Navigation
      statement: 'What does VOR stand for?',
      explanation: 'VOR stands for VHF Omnidirectional Range, a type of radio navigation system.',
      difficulty: 2,
      alternatives: [
        { text: 'Very Old Radio', isCorrect: false },
        { text: 'VHF Omnidirectional Range', isCorrect: true },
        { text: 'Vertical Orientation Reference', isCorrect: false },
        { text: 'Voice Over Radio', isCorrect: false },
      ],
    },
    {
      uniqueKey: 'navigation-ils-purpose',
      tagId: tags[1].id, // Navigation
      statement: 'What is the primary purpose of an ILS system?',
      explanation: 'ILS (Instrument Landing System) provides precision guidance for landing in low visibility conditions.',
      difficulty: 3,
      alternatives: [
        { text: 'Weather reporting', isCorrect: false },
        { text: 'Precision landing guidance', isCorrect: true },
        { text: 'Communication with ATC', isCorrect: false },
        { text: 'Fuel management', isCorrect: false },
      ],
    },
    {
      uniqueKey: 'meteorology-thunderstorm-clouds',
      tagId: tags[2].id, // Meteorology
      statement: 'What type of cloud is most likely to produce thunderstorms?',
      explanation: 'Cumulonimbus clouds are the primary cloud type associated with thunderstorms.',
      difficulty: 2,
      alternatives: [
        { text: 'Stratus', isCorrect: false },
        { text: 'Cumulus', isCorrect: false },
        { text: 'Cumulonimbus', isCorrect: true },
        { text: 'Cirrus', isCorrect: false },
      ],
    },
    {
      uniqueKey: 'meteorology-standard-pressure',
      tagId: tags[2].id, // Meteorology
      statement: 'What is the standard atmospheric pressure at sea level?',
      explanation: 'Standard atmospheric pressure at sea level is 1013.25 hPa or 29.92 inches of mercury.',
      difficulty: 3,
      alternatives: [
        { text: '1000 hPa', isCorrect: false },
        { text: '1013.25 hPa', isCorrect: true },
        { text: '1050 hPa', isCorrect: false },
        { text: '950 hPa', isCorrect: false },
      ],
    },
    {
      uniqueKey: 'regulations-vfr-visibility',
      tagId: tags[3].id, // Regulations
      statement: 'What is the minimum visibility required for VFR flight in controlled airspace?',
      explanation: 'In controlled airspace, VFR flight requires at least 3 statute miles visibility.',
      difficulty: 3,
      alternatives: [
        { text: '1 mile', isCorrect: false },
        { text: '2 miles', isCorrect: false },
        { text: '3 miles', isCorrect: true },
        { text: '5 miles', isCorrect: false },
      ],
    },
    {
      uniqueKey: 'regulations-speed-limit-10000',
      tagId: tags[3].id, // Regulations
      statement: 'What is the maximum speed limit below 10,000 feet MSL?',
      explanation: 'The maximum speed limit below 10,000 feet MSL is 250 knots.',
      difficulty: 2,
      alternatives: [
        { text: '200 knots', isCorrect: false },
        { text: '250 knots', isCorrect: true },
        { text: '300 knots', isCorrect: false },
        { text: '350 knots', isCorrect: false },
      ],
    },
  ];

  for (const questionData of questions) {
    const { alternatives, ...questionFields } = questionData;
    
    // First, try to find existing question by statement
    const existingQuestion = await prisma.question.findFirst({
      where: { statement: questionFields.statement },
    });

    if (existingQuestion) {
      // Update existing question
      await prisma.question.update({
        where: { id: existingQuestion.id },
        data: {
          ...questionFields,
          alternatives: {
            deleteMany: {},
            create: alternatives,
          },
        },
      });
      console.log(`🔄 Updated question: ${questionFields.statement.substring(0, 50)}...`);
    } else {
      // Create new question
      await prisma.question.create({
        data: {
          ...questionFields,
          alternatives: {
            create: alternatives,
          },
        },
      });
      console.log(`✅ Created question: ${questionFields.statement.substring(0, 50)}...`);
    }
  }

  console.log(`✅ Processed ${questions.length} questions`);

  // Create sample exam template using findFirst + upsert approach
  const existingTemplate = await prisma.examTemplate.findFirst({
    where: { title: 'Basic Aviation Knowledge Test' },
  });

  let examTemplate;
  if (existingTemplate) {
    // Update existing template
    examTemplate = await prisma.examTemplate.update({
      where: { id: existingTemplate.id },
      data: {
        description: 'A comprehensive test covering fundamental aviation concepts',
        questionCount: 8,
        timeLimit: 30, // 30 minutes
        passingScore: 70, // 70%
        examTemplateTags: {
          deleteMany: {},
          create: [
            { questionTagId: tags[0].id, questionCount: 2 }, // 2 Aerodynamics questions
            { questionTagId: tags[1].id, questionCount: 2 }, // 2 Navigation questions
            { questionTagId: tags[2].id, questionCount: 2 }, // 2 Meteorology questions
            { questionTagId: tags[3].id, questionCount: 2 }, // 2 Regulations questions
          ],
        },
      },
    });
    console.log(`🔄 Updated exam template: ${examTemplate.title}`);
  } else {
    // Create new template
    examTemplate = await prisma.examTemplate.create({
      data: {
        title: 'Basic Aviation Knowledge Test',
        description: 'A comprehensive test covering fundamental aviation concepts',
        questionCount: 8,
        timeLimit: 30, // 30 minutes
        passingScore: 70, // 70%
        examTemplateTags: {
          create: [
            { questionTagId: tags[0].id, questionCount: 2 }, // 2 Aerodynamics questions
            { questionTagId: tags[1].id, questionCount: 2 }, // 2 Navigation questions
            { questionTagId: tags[2].id, questionCount: 2 }, // 2 Meteorology questions
            { questionTagId: tags[3].id, questionCount: 2 }, // 2 Regulations questions
          ],
        },
      },
    });
    console.log(`✅ Created exam template: ${examTemplate.title}`);
  }

  console.log('🎉 Exam system seeding completed!');
}

main()
  .catch((e) => {
    console.error('❌ Error seeding exam system:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
