// This file is automatically generated by a script. DO NOT EDIT DIRECTLY.

import { Event } from '@prisma/client'; // Adjust path if needed
import { SeverityId } from './severity'; // Path relative to generatedCheckList.ts

// Event type including the logical ID. Extend Prisma's Event model.
export interface GeneratedEvent extends Event {
  logicalId: string; // The ID generated for the checklist navigation
  name: string;
  reference: string;
  description: string;
}

// Maps sequential IDs (e.g., "01") to GeneratedEvent objects
type SequentialIdMap = {
  [key: string]: GeneratedEvent;
};

// =========================================================
// DYNAMICALLY GENERATED INTERFACES FOR LITERAL KEYS
// =========================================================

// SeverityMap: Uses fixed keys from the SeverityId enum
type SeverityMap = {
  STANDARD_COMPLIANCE: SequentialIdMap;
  PROACTIVE_EXCELLENCE: SequentialIdMap;
  PROCEDURAL_DEVIATION: SequentialIdMap;
  SAFETY_COMPROMISE: SequentialIdMap;
};

export type ItemMapFor_AT_START_CLEARANCE = {
  PUSHBACKSTART_UP_CLEARANCE: SeverityMap;
  WINDOWS_AND_DOORS: SeverityMap;
  EXTERIOR_LIGHTS: SeverityMap;
  THRUST_LEVERS: SeverityMap;
  ACCU_PRESSURE: SeverityMap;
  PARKING_BRAKE_AND_NOSEWHEEL_STEERING: SeverityMap;
};

export type ItemMapFor_AFTER_ENGINE_START = {
  ENGINES: SeverityMap;
};

export type SubPhaseMapFor_BEFORE_PUSHBACK_OR_START = {
  AT_START_CLEARANCE: ItemMapFor_AT_START_CLEARANCE;
};

export type SubPhaseMapFor_AFTER_ENGINE_START = {
  AFTER_ENGINE_START: ItemMapFor_AFTER_ENGINE_START;
};

// Fallback type for generic item map when no specific type can be generated
type ItemMapFor_Generic = {
  [key: string]: SeverityMap;
};

// Main CheckListOutput type with literal phase keys
export type CheckListOutput = {
  BEFORE_PUSHBACK_OR_START: SubPhaseMapFor_BEFORE_PUSHBACK_OR_START;
  AFTER_ENGINE_START: SubPhaseMapFor_AFTER_ENGINE_START;
};

export const checkList: CheckListOutput = {
  BEFORE_PUSHBACK_OR_START: {
    AT_START_CLEARANCE: {
      PUSHBACKSTART_UP_CLEARANCE: {
        STANDARD_COMPLIANCE: {},
        PROACTIVE_EXCELLENCE: {},
        PROCEDURAL_DEVIATION: {},
        SAFETY_COMPROMISE: {},
      },
      WINDOWS_AND_DOORS: {
        STANDARD_COMPLIANCE: {},
        PROACTIVE_EXCELLENCE: {},
        PROCEDURAL_DEVIATION: {},
        SAFETY_COMPROMISE: {},
      },
      EXTERIOR_LIGHTS: {
        STANDARD_COMPLIANCE: {},
        PROACTIVE_EXCELLENCE: {},
        PROCEDURAL_DEVIATION: {},
        SAFETY_COMPROMISE: {},
      },
      THRUST_LEVERS: {
        STANDARD_COMPLIANCE: {},
        PROACTIVE_EXCELLENCE: {},
        PROCEDURAL_DEVIATION: {},
        SAFETY_COMPROMISE: {},
      },
      ACCU_PRESSURE: {
        STANDARD_COMPLIANCE: {
          '01': {
            id: 'placeholder-prisma-id',
            logicalId:
              '[BEFORE_PUSHBACK_OR_START][AT_START_CLEARANCE][ACCU_PRESSURE][STANDARD_COMPLIANCE][01]',
            name: 'ACCU PRESS indicator',
            reference: '',
            description: 'green band',
            severityId: 1,
          },
        },
        PROACTIVE_EXCELLENCE: {},
        PROCEDURAL_DEVIATION: {},
        SAFETY_COMPROMISE: {
          '01': {
            id: 'placeholder-prisma-id',
            logicalId:
              '[BEFORE_PUSHBACK_OR_START][AT_START_CLEARANCE][ACCU_PRESSURE][SAFETY_COMPROMISE][01]',
            name: 'ACCU PRESS indicator',
            reference: '',
            description:
              '\n<p>Quando a indicação da pressão do ACCU (Acumulador) está fora da faixa verde, significa que a pressão hidráulica armazenada nos acumuladores de freio é insuficiente. Isso tem implicações diretas e críticas para a segurança operacional:</p>\n\n<ul>\n    <li><strong>Risco de movimento descontrolado da aeronave:</strong> A baixa pressão do acumulador limita a força de atrito aplicada nos discos de freio, o que pode levar a um movimento indesejado da aeronave, especialmente durante o pushback, quando os motores ainda não estão fornecendo pressão hidráulica total.</li>\n    <li><strong>Ineficácia do freio de estacionamento:</strong> O freio de estacionamento depende diretamente da pressão hidráulica fornecida pelos acumuladores quando os motores não estão em funcionamento. Se a pressão do ACCU estiver baixa, o freio de estacionamento não conseguirá manter a aeronave parada com segurança, permitindo que ela role livremente.</li>\n    <li><strong>Comprometimento das aplicações de frenagem de emergência:</strong> Os acumuladores fornecem uma reserva crítica de energia para um número limitado de aplicações de frenagem, especialmente em cenários onde as fontes primárias de potência hidráulica não estão operacionais. Se a pressão do ACCU já estiver baixa antes do pushback, essa margem de segurança é severamente reduzida, limitando o número de aplicações de freio disponíveis em uma emergência, como um pushback abortado ou uma falha hidráulica subsequente.</li>\n</ul>\n\n<p>Em resumo, uma indicação fora da faixa verde não é apenas um desvio técnico, mas um alerta direto para uma capacidade de frenagem comprometida, o que eleva o risco de incidentes em solo e compromete a segurança geral da operação.</p>',
            severityId: 4,
          },
        },
      },
      PARKING_BRAKE_AND_NOSEWHEEL_STEERING: {
        STANDARD_COMPLIANCE: {},
        PROACTIVE_EXCELLENCE: {},
        PROCEDURAL_DEVIATION: {},
        SAFETY_COMPROMISE: {},
      },
    },
  },
  AFTER_ENGINE_START: {
    AFTER_ENGINE_START: {
      ENGINES: {
        STANDARD_COMPLIANCE: {
          '01': {
            id: 'placeholder-prisma-id',
            logicalId:
              '[AFTER_ENGINE_START][AFTER_ENGINE_START][ENGINES][STANDARD_COMPLIANCE][01]',
            name: 'Engine start successful',
            reference: 'ENG-1',
            description: 'Both engines are running within normal parameters.',
            severityId: 1,
          },
        },
        PROACTIVE_EXCELLENCE: {},
        PROCEDURAL_DEVIATION: {},
        SAFETY_COMPROMISE: {},
      },
    },
  },
};
