/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as CreateAccountImport } from './routes/create-account'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthResourcesImport } from './routes/_auth/resources'
import { Route as AuthProfileImport } from './routes/_auth/profile'
import { Route as AuthFlightDutyImport } from './routes/_auth/flight-duty'
import { Route as AuthExamImport } from './routes/_auth/exam'
import { Route as AuthAwardsImport } from './routes/_auth/awards'
import { Route as AuthAdminImport } from './routes/_auth/_admin'
import { Route as AuthMainIndexImport } from './routes/_auth/main/index'
import { Route as AuthLogbookIndexImport } from './routes/_auth/logbook/index'
import { Route as AuthFlightDetailsFlightIdImport } from './routes/_auth/flight-details.$flightId'
import { Route as AuthAdminAdminIndexImport } from './routes/_auth/_admin/admin/index'
import { Route as AuthAdminAdminRoutesImport } from './routes/_auth/_admin/admin/routes'
import { Route as AuthAdminAdminQuestionsImport } from './routes/_auth/_admin/admin/questions'
import { Route as AuthAdminAdminQuestionTagsImport } from './routes/_auth/_admin/admin/question-tags'
import { Route as AuthAdminAdminExamsImport } from './routes/_auth/_admin/admin/exams'
import { Route as AuthAdminAdminEventsImport } from './routes/_auth/_admin/admin/events'
import { Route as AuthAdminAdminExamTemplatesIndexImport } from './routes/_auth/_admin/admin/exam-templates/index'
import { Route as AuthAdminAdminExamTemplatesCreateExamTemplateImport } from './routes/_auth/_admin/admin/exam-templates/create-exam-template'
import { Route as AuthAdminAdminExamTemplatesExamTemplateIdImport } from './routes/_auth/_admin/admin/exam-templates/$examTemplateId'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const CreateAccountRoute = CreateAccountImport.update({
  path: '/create-account',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AuthResourcesRoute = AuthResourcesImport.update({
  path: '/resources',
  getParentRoute: () => AuthRoute,
} as any)

const AuthProfileRoute = AuthProfileImport.update({
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)

const AuthFlightDutyRoute = AuthFlightDutyImport.update({
  path: '/flight-duty',
  getParentRoute: () => AuthRoute,
} as any)

const AuthExamRoute = AuthExamImport.update({
  path: '/exam',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAwardsRoute = AuthAwardsImport.update({
  path: '/awards',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAdminRoute = AuthAdminImport.update({
  id: '/_admin',
  getParentRoute: () => AuthRoute,
} as any)

const AuthMainIndexRoute = AuthMainIndexImport.update({
  path: '/main/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLogbookIndexRoute = AuthLogbookIndexImport.update({
  path: '/logbook/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthFlightDetailsFlightIdRoute = AuthFlightDetailsFlightIdImport.update({
  path: '/flight-details/$flightId',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAdminAdminIndexRoute = AuthAdminAdminIndexImport.update({
  path: '/admin/',
  getParentRoute: () => AuthAdminRoute,
} as any)

const AuthAdminAdminRoutesRoute = AuthAdminAdminRoutesImport.update({
  path: '/admin/routes',
  getParentRoute: () => AuthAdminRoute,
} as any)

const AuthAdminAdminQuestionsRoute = AuthAdminAdminQuestionsImport.update({
  path: '/admin/questions',
  getParentRoute: () => AuthAdminRoute,
} as any)

const AuthAdminAdminQuestionTagsRoute = AuthAdminAdminQuestionTagsImport.update(
  {
    path: '/admin/question-tags',
    getParentRoute: () => AuthAdminRoute,
  } as any,
)

const AuthAdminAdminExamsRoute = AuthAdminAdminExamsImport.update({
  path: '/admin/exams',
  getParentRoute: () => AuthAdminRoute,
} as any)

const AuthAdminAdminEventsRoute = AuthAdminAdminEventsImport.update({
  path: '/admin/events',
  getParentRoute: () => AuthAdminRoute,
} as any)

const AuthAdminAdminExamTemplatesIndexRoute =
  AuthAdminAdminExamTemplatesIndexImport.update({
    path: '/admin/exam-templates/',
    getParentRoute: () => AuthAdminRoute,
  } as any)

const AuthAdminAdminExamTemplatesCreateExamTemplateRoute =
  AuthAdminAdminExamTemplatesCreateExamTemplateImport.update({
    path: '/admin/exam-templates/create-exam-template',
    getParentRoute: () => AuthAdminRoute,
  } as any)

const AuthAdminAdminExamTemplatesExamTemplateIdRoute =
  AuthAdminAdminExamTemplatesExamTemplateIdImport.update({
    path: '/admin/exam-templates/$examTemplateId',
    getParentRoute: () => AuthAdminRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/create-account': {
      id: '/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof CreateAccountImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_admin': {
      id: '/_auth/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthAdminImport
      parentRoute: typeof AuthImport
    }
    '/_auth/awards': {
      id: '/_auth/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AuthAwardsImport
      parentRoute: typeof AuthImport
    }
    '/_auth/exam': {
      id: '/_auth/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof AuthExamImport
      parentRoute: typeof AuthImport
    }
    '/_auth/flight-duty': {
      id: '/_auth/flight-duty'
      path: '/flight-duty'
      fullPath: '/flight-duty'
      preLoaderRoute: typeof AuthFlightDutyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileImport
      parentRoute: typeof AuthImport
    }
    '/_auth/resources': {
      id: '/_auth/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthResourcesImport
      parentRoute: typeof AuthImport
    }
    '/_auth/flight-details/$flightId': {
      id: '/_auth/flight-details/$flightId'
      path: '/flight-details/$flightId'
      fullPath: '/flight-details/$flightId'
      preLoaderRoute: typeof AuthFlightDetailsFlightIdImport
      parentRoute: typeof AuthImport
    }
    '/_auth/logbook/': {
      id: '/_auth/logbook/'
      path: '/logbook'
      fullPath: '/logbook'
      preLoaderRoute: typeof AuthLogbookIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/main/': {
      id: '/_auth/main/'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof AuthMainIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/_admin/admin/events': {
      id: '/_auth/_admin/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthAdminAdminEventsImport
      parentRoute: typeof AuthAdminImport
    }
    '/_auth/_admin/admin/exams': {
      id: '/_auth/_admin/admin/exams'
      path: '/admin/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AuthAdminAdminExamsImport
      parentRoute: typeof AuthAdminImport
    }
    '/_auth/_admin/admin/question-tags': {
      id: '/_auth/_admin/admin/question-tags'
      path: '/admin/question-tags'
      fullPath: '/admin/question-tags'
      preLoaderRoute: typeof AuthAdminAdminQuestionTagsImport
      parentRoute: typeof AuthAdminImport
    }
    '/_auth/_admin/admin/questions': {
      id: '/_auth/_admin/admin/questions'
      path: '/admin/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AuthAdminAdminQuestionsImport
      parentRoute: typeof AuthAdminImport
    }
    '/_auth/_admin/admin/routes': {
      id: '/_auth/_admin/admin/routes'
      path: '/admin/routes'
      fullPath: '/admin/routes'
      preLoaderRoute: typeof AuthAdminAdminRoutesImport
      parentRoute: typeof AuthAdminImport
    }
    '/_auth/_admin/admin/': {
      id: '/_auth/_admin/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminAdminIndexImport
      parentRoute: typeof AuthAdminImport
    }
    '/_auth/_admin/admin/exam-templates/$examTemplateId': {
      id: '/_auth/_admin/admin/exam-templates/$examTemplateId'
      path: '/admin/exam-templates/$examTemplateId'
      fullPath: '/admin/exam-templates/$examTemplateId'
      preLoaderRoute: typeof AuthAdminAdminExamTemplatesExamTemplateIdImport
      parentRoute: typeof AuthAdminImport
    }
    '/_auth/_admin/admin/exam-templates/create-exam-template': {
      id: '/_auth/_admin/admin/exam-templates/create-exam-template'
      path: '/admin/exam-templates/create-exam-template'
      fullPath: '/admin/exam-templates/create-exam-template'
      preLoaderRoute: typeof AuthAdminAdminExamTemplatesCreateExamTemplateImport
      parentRoute: typeof AuthAdminImport
    }
    '/_auth/_admin/admin/exam-templates/': {
      id: '/_auth/_admin/admin/exam-templates/'
      path: '/admin/exam-templates'
      fullPath: '/admin/exam-templates'
      preLoaderRoute: typeof AuthAdminAdminExamTemplatesIndexImport
      parentRoute: typeof AuthAdminImport
    }
  }
}

// Create and export the route tree

interface AuthAdminRouteChildren {
  AuthAdminAdminEventsRoute: typeof AuthAdminAdminEventsRoute
  AuthAdminAdminExamsRoute: typeof AuthAdminAdminExamsRoute
  AuthAdminAdminQuestionTagsRoute: typeof AuthAdminAdminQuestionTagsRoute
  AuthAdminAdminQuestionsRoute: typeof AuthAdminAdminQuestionsRoute
  AuthAdminAdminRoutesRoute: typeof AuthAdminAdminRoutesRoute
  AuthAdminAdminIndexRoute: typeof AuthAdminAdminIndexRoute
  AuthAdminAdminExamTemplatesExamTemplateIdRoute: typeof AuthAdminAdminExamTemplatesExamTemplateIdRoute
  AuthAdminAdminExamTemplatesCreateExamTemplateRoute: typeof AuthAdminAdminExamTemplatesCreateExamTemplateRoute
  AuthAdminAdminExamTemplatesIndexRoute: typeof AuthAdminAdminExamTemplatesIndexRoute
}

const AuthAdminRouteChildren: AuthAdminRouteChildren = {
  AuthAdminAdminEventsRoute: AuthAdminAdminEventsRoute,
  AuthAdminAdminExamsRoute: AuthAdminAdminExamsRoute,
  AuthAdminAdminQuestionTagsRoute: AuthAdminAdminQuestionTagsRoute,
  AuthAdminAdminQuestionsRoute: AuthAdminAdminQuestionsRoute,
  AuthAdminAdminRoutesRoute: AuthAdminAdminRoutesRoute,
  AuthAdminAdminIndexRoute: AuthAdminAdminIndexRoute,
  AuthAdminAdminExamTemplatesExamTemplateIdRoute:
    AuthAdminAdminExamTemplatesExamTemplateIdRoute,
  AuthAdminAdminExamTemplatesCreateExamTemplateRoute:
    AuthAdminAdminExamTemplatesCreateExamTemplateRoute,
  AuthAdminAdminExamTemplatesIndexRoute: AuthAdminAdminExamTemplatesIndexRoute,
}

const AuthAdminRouteWithChildren = AuthAdminRoute._addFileChildren(
  AuthAdminRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRouteWithChildren
  AuthAwardsRoute: typeof AuthAwardsRoute
  AuthExamRoute: typeof AuthExamRoute
  AuthFlightDutyRoute: typeof AuthFlightDutyRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthResourcesRoute: typeof AuthResourcesRoute
  AuthFlightDetailsFlightIdRoute: typeof AuthFlightDetailsFlightIdRoute
  AuthLogbookIndexRoute: typeof AuthLogbookIndexRoute
  AuthMainIndexRoute: typeof AuthMainIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRouteWithChildren,
  AuthAwardsRoute: AuthAwardsRoute,
  AuthExamRoute: AuthExamRoute,
  AuthFlightDutyRoute: AuthFlightDutyRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthResourcesRoute: AuthResourcesRoute,
  AuthFlightDetailsFlightIdRoute: AuthFlightDetailsFlightIdRoute,
  AuthLogbookIndexRoute: AuthLogbookIndexRoute,
  AuthMainIndexRoute: AuthMainIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '': typeof AuthAdminRouteWithChildren
  '/create-account': typeof CreateAccountRoute
  '/login': typeof LoginRoute
  '/about': typeof AboutLazyRoute
  '/awards': typeof AuthAwardsRoute
  '/exam': typeof AuthExamRoute
  '/flight-duty': typeof AuthFlightDutyRoute
  '/profile': typeof AuthProfileRoute
  '/resources': typeof AuthResourcesRoute
  '/flight-details/$flightId': typeof AuthFlightDetailsFlightIdRoute
  '/logbook': typeof AuthLogbookIndexRoute
  '/main': typeof AuthMainIndexRoute
  '/admin/events': typeof AuthAdminAdminEventsRoute
  '/admin/exams': typeof AuthAdminAdminExamsRoute
  '/admin/question-tags': typeof AuthAdminAdminQuestionTagsRoute
  '/admin/questions': typeof AuthAdminAdminQuestionsRoute
  '/admin/routes': typeof AuthAdminAdminRoutesRoute
  '/admin': typeof AuthAdminAdminIndexRoute
  '/admin/exam-templates/$examTemplateId': typeof AuthAdminAdminExamTemplatesExamTemplateIdRoute
  '/admin/exam-templates/create-exam-template': typeof AuthAdminAdminExamTemplatesCreateExamTemplateRoute
  '/admin/exam-templates': typeof AuthAdminAdminExamTemplatesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '': typeof AuthAdminRouteWithChildren
  '/create-account': typeof CreateAccountRoute
  '/login': typeof LoginRoute
  '/about': typeof AboutLazyRoute
  '/awards': typeof AuthAwardsRoute
  '/exam': typeof AuthExamRoute
  '/flight-duty': typeof AuthFlightDutyRoute
  '/profile': typeof AuthProfileRoute
  '/resources': typeof AuthResourcesRoute
  '/flight-details/$flightId': typeof AuthFlightDetailsFlightIdRoute
  '/logbook': typeof AuthLogbookIndexRoute
  '/main': typeof AuthMainIndexRoute
  '/admin/events': typeof AuthAdminAdminEventsRoute
  '/admin/exams': typeof AuthAdminAdminExamsRoute
  '/admin/question-tags': typeof AuthAdminAdminQuestionTagsRoute
  '/admin/questions': typeof AuthAdminAdminQuestionsRoute
  '/admin/routes': typeof AuthAdminAdminRoutesRoute
  '/admin': typeof AuthAdminAdminIndexRoute
  '/admin/exam-templates/$examTemplateId': typeof AuthAdminAdminExamTemplatesExamTemplateIdRoute
  '/admin/exam-templates/create-exam-template': typeof AuthAdminAdminExamTemplatesCreateExamTemplateRoute
  '/admin/exam-templates': typeof AuthAdminAdminExamTemplatesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/_auth': typeof AuthRouteWithChildren
  '/create-account': typeof CreateAccountRoute
  '/login': typeof LoginRoute
  '/about': typeof AboutLazyRoute
  '/_auth/_admin': typeof AuthAdminRouteWithChildren
  '/_auth/awards': typeof AuthAwardsRoute
  '/_auth/exam': typeof AuthExamRoute
  '/_auth/flight-duty': typeof AuthFlightDutyRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/resources': typeof AuthResourcesRoute
  '/_auth/flight-details/$flightId': typeof AuthFlightDetailsFlightIdRoute
  '/_auth/logbook/': typeof AuthLogbookIndexRoute
  '/_auth/main/': typeof AuthMainIndexRoute
  '/_auth/_admin/admin/events': typeof AuthAdminAdminEventsRoute
  '/_auth/_admin/admin/exams': typeof AuthAdminAdminExamsRoute
  '/_auth/_admin/admin/question-tags': typeof AuthAdminAdminQuestionTagsRoute
  '/_auth/_admin/admin/questions': typeof AuthAdminAdminQuestionsRoute
  '/_auth/_admin/admin/routes': typeof AuthAdminAdminRoutesRoute
  '/_auth/_admin/admin/': typeof AuthAdminAdminIndexRoute
  '/_auth/_admin/admin/exam-templates/$examTemplateId': typeof AuthAdminAdminExamTemplatesExamTemplateIdRoute
  '/_auth/_admin/admin/exam-templates/create-exam-template': typeof AuthAdminAdminExamTemplatesCreateExamTemplateRoute
  '/_auth/_admin/admin/exam-templates/': typeof AuthAdminAdminExamTemplatesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/create-account'
    | '/login'
    | '/about'
    | '/awards'
    | '/exam'
    | '/flight-duty'
    | '/profile'
    | '/resources'
    | '/flight-details/$flightId'
    | '/logbook'
    | '/main'
    | '/admin/events'
    | '/admin/exams'
    | '/admin/question-tags'
    | '/admin/questions'
    | '/admin/routes'
    | '/admin'
    | '/admin/exam-templates/$examTemplateId'
    | '/admin/exam-templates/create-exam-template'
    | '/admin/exam-templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/create-account'
    | '/login'
    | '/about'
    | '/awards'
    | '/exam'
    | '/flight-duty'
    | '/profile'
    | '/resources'
    | '/flight-details/$flightId'
    | '/logbook'
    | '/main'
    | '/admin/events'
    | '/admin/exams'
    | '/admin/question-tags'
    | '/admin/questions'
    | '/admin/routes'
    | '/admin'
    | '/admin/exam-templates/$examTemplateId'
    | '/admin/exam-templates/create-exam-template'
    | '/admin/exam-templates'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/create-account'
    | '/login'
    | '/about'
    | '/_auth/_admin'
    | '/_auth/awards'
    | '/_auth/exam'
    | '/_auth/flight-duty'
    | '/_auth/profile'
    | '/_auth/resources'
    | '/_auth/flight-details/$flightId'
    | '/_auth/logbook/'
    | '/_auth/main/'
    | '/_auth/_admin/admin/events'
    | '/_auth/_admin/admin/exams'
    | '/_auth/_admin/admin/question-tags'
    | '/_auth/_admin/admin/questions'
    | '/_auth/_admin/admin/routes'
    | '/_auth/_admin/admin/'
    | '/_auth/_admin/admin/exam-templates/$examTemplateId'
    | '/_auth/_admin/admin/exam-templates/create-exam-template'
    | '/_auth/_admin/admin/exam-templates/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AuthRoute: typeof AuthRouteWithChildren
  CreateAccountRoute: typeof CreateAccountRoute
  LoginRoute: typeof LoginRoute
  AboutLazyRoute: typeof AboutLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AuthRoute: AuthRouteWithChildren,
  CreateAccountRoute: CreateAccountRoute,
  LoginRoute: LoginRoute,
  AboutLazyRoute: AboutLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/create-account",
        "/login",
        "/about"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/_admin",
        "/_auth/awards",
        "/_auth/exam",
        "/_auth/flight-duty",
        "/_auth/profile",
        "/_auth/resources",
        "/_auth/flight-details/$flightId",
        "/_auth/logbook/",
        "/_auth/main/"
      ]
    },
    "/create-account": {
      "filePath": "create-account.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/_auth/_admin": {
      "filePath": "_auth/_admin.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/_admin/admin/events",
        "/_auth/_admin/admin/exams",
        "/_auth/_admin/admin/question-tags",
        "/_auth/_admin/admin/questions",
        "/_auth/_admin/admin/routes",
        "/_auth/_admin/admin/",
        "/_auth/_admin/admin/exam-templates/$examTemplateId",
        "/_auth/_admin/admin/exam-templates/create-exam-template",
        "/_auth/_admin/admin/exam-templates/"
      ]
    },
    "/_auth/awards": {
      "filePath": "_auth/awards.tsx",
      "parent": "/_auth"
    },
    "/_auth/exam": {
      "filePath": "_auth/exam.tsx",
      "parent": "/_auth"
    },
    "/_auth/flight-duty": {
      "filePath": "_auth/flight-duty.tsx",
      "parent": "/_auth"
    },
    "/_auth/profile": {
      "filePath": "_auth/profile.tsx",
      "parent": "/_auth"
    },
    "/_auth/resources": {
      "filePath": "_auth/resources.tsx",
      "parent": "/_auth"
    },
    "/_auth/flight-details/$flightId": {
      "filePath": "_auth/flight-details.$flightId.tsx",
      "parent": "/_auth"
    },
    "/_auth/logbook/": {
      "filePath": "_auth/logbook/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/main/": {
      "filePath": "_auth/main/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/_admin/admin/events": {
      "filePath": "_auth/_admin/admin/events.tsx",
      "parent": "/_auth/_admin"
    },
    "/_auth/_admin/admin/exams": {
      "filePath": "_auth/_admin/admin/exams.tsx",
      "parent": "/_auth/_admin"
    },
    "/_auth/_admin/admin/question-tags": {
      "filePath": "_auth/_admin/admin/question-tags.tsx",
      "parent": "/_auth/_admin"
    },
    "/_auth/_admin/admin/questions": {
      "filePath": "_auth/_admin/admin/questions.tsx",
      "parent": "/_auth/_admin"
    },
    "/_auth/_admin/admin/routes": {
      "filePath": "_auth/_admin/admin/routes.tsx",
      "parent": "/_auth/_admin"
    },
    "/_auth/_admin/admin/": {
      "filePath": "_auth/_admin/admin/index.tsx",
      "parent": "/_auth/_admin"
    },
    "/_auth/_admin/admin/exam-templates/$examTemplateId": {
      "filePath": "_auth/_admin/admin/exam-templates/$examTemplateId.tsx",
      "parent": "/_auth/_admin"
    },
    "/_auth/_admin/admin/exam-templates/create-exam-template": {
      "filePath": "_auth/_admin/admin/exam-templates/create-exam-template.tsx",
      "parent": "/_auth/_admin"
    },
    "/_auth/_admin/admin/exam-templates/": {
      "filePath": "_auth/_admin/admin/exam-templates/index.tsx",
      "parent": "/_auth/_admin"
    }
  }
}
ROUTE_MANIFEST_END */
