import {
  Body,
  Controller,
  Get,
  Query,
  Put,
  UseGuards,
  Param,
  ParseIntPipe,
} from '@nestjs/common';
import { UserService } from '../services/user.service';
import { AuthGuard } from '../../../common/guards/auth.guard';
import { GetUser } from '../../../common/decorator/getUser.decorator';
import { UpdateUserBaseDto } from '../dto/user.dto';
import { FlightDutyService } from '../../flightDuty/services/flightDuty.service';

type GetUserBy = {
  id?: string;
  usernameOrEmail?: string;
};

type UpdatePlanDto = {
  plan: 'FREE' | 'GOLD';
};

@Controller('user')
export class UserController {
  constructor(
    private userService: UserService,
    private flightDutyService: FlightDutyService,
  ) {}

  @Get()
  async checkIfUsernameOrEmailExists(@Query() query: GetUserBy) {
    if (query.usernameOrEmail) {
      return this.userService.checkIfUsernameExists(query.usernameOrEmail);
    }

    throw new Error('Invalid request');
  }

  @Put('plan')
  @UseGuards(AuthGuard)
  async updatePlan(@Body() updatePlanDto: UpdatePlanDto, @GetUser() user: any) {
    return this.userService.updateUserPlan(user.id, updatePlanDto.plan);
  }

  @Put('base')
  @UseGuards(AuthGuard)
  async updateBase(
    @Body() updateBaseDto: UpdateUserBaseDto,
    @GetUser() user: any,
  ) {
    return this.userService.updateUserBase(user.id, updateBaseDto.baseId);
  }

  @Put(':id/subsidiary-base')
  @UseGuards(AuthGuard)
  async updateSubsidiaryAndBase(
    @Param('id', ParseIntPipe) userId: number,
    @Body() updateDto: { subsidiaryId: number; baseId: number },
    @GetUser() user: any,
  ) {
    // Ensure user can only update their own profile
    if (user.id !== userId) {
      throw new Error('Unauthorized');
    }

    // Check if user has open flight duty
    const hasOpenFlightDuty =
      await this.flightDutyService.hasOpenFlightDuty(userId);
    if (hasOpenFlightDuty) {
      throw new Error(
        'Cannot update subsidiary and base while you have an open flight duty',
      );
    }

    const updatedUser = await this.userService.updateUserSubsidiaryAndBase(
      userId,
      updateDto.subsidiaryId,
      updateDto.baseId,
    );

    // Generate new token with updated user data
    return {
      user: updatedUser,
      authToken: 'updated-token', // This should be generated by auth service
    };
  }
}
